# Exploration des données

Ce notebook présente les données du challenge et les analyse.

In [1]:
import pandas as pd
import seaborn as sns

In [2]:
# Extraction des données
X = pd.read_csv('../data/raw/x_train_final.csv')
y = pd.read_csv('../data/raw/y_train_final_j5KGWWK.csv')

X.head()

,Unnamed: 0.1,Unnamed: 0,train,gare,date,arret,p2q0,p3q0,p4q0,p0q2,p0q3,p0q4
0,0,0,VBXNMF,KYF,2023-04-03,8,0.0,0.0,1.0,-3.0,-1.0,-2.0
1,1,1,VBXNMF,JLR,2023-04-03,9,0.0,0.0,0.0,1.0,0.0,1.0
2,2,2,VBXNMF,EOH,2023-04-03,10,-1.0,0.0,0.0,-1.0,0.0,0.0
3,3,3,VBXNMF,VXY,2023-04-03,11,-1.0,-1.0,0.0,2.0,-2.0,0.0
4,4,4,VBXNMF,OCB,2023-04-03,12,-1.0,-1.0,-1.0,-1.0,3.0,2.0

In [3]:
# Suppression des colonnes du triplon d'index 

X = X.drop(columns=['Unnamed: 0.1', 'Unnamed: 0'])
y = y.drop(columns=['Unnamed: 0'])

X.head()

    train gare        date  arret  p2q0  p3q0  p4q0  p0q2  p0q3  p0q4
0  VBXNMF  KYF  2023-04-03      8   0.0   0.0   1.0  -3.0  -1.0  -2.0
1  VBXNMF  JLR  2023-04-03      9   0.0   0.0   0.0   1.0   0.0   1.0
2  VBXNMF  EOH  2023-04-03     10  -1.0   0.0   0.0  -1.0   0.0   0.0
3  VBXNMF  VXY  2023-04-03     11  -1.0  -1.0   0.0   2.0  -2.0   0.0
4  VBXNMF  OCB  2023-04-03     12  -1.0  -1.0  -1.0  -1.0   3.0   2.0

In [4]:
# Détection des données dupliquées
X.duplicated().sum()

np.int64(0)

In [5]:
# Détection des données vides ou incomplètes
pd.concat([X, y], axis = 1).isnull().any()

train    False
gare     False
date     False
arret    False
p2q0     False
p3q0     False
p4q0     False
p0q2     False
p0q3     False
p0q4     False
p0q0     False
dtype: bool

In [11]:
df_data = pd.concat([X, y], axis = 1)
df_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 667264 entries, 0 to 667263
Data columns (total 11 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   train   667264 non-null  object
 1   gare    667264 non-null  object
 2   date    667264 non-null  datetime64[ns]
 3   arret   667264 non-null  int64
 4   p2q0    667264 non-null  float64
 5   p3q0    667264 non-null  float64
 6   p4q0    667264 non-null  float64
 7   p0q2    667264 non-null  float64
 8   p0q3    667264 non-null  float64
 9   p0q4    667264 non-null  float64
 10  p0q0    667264 non-null  float64
dtypes: datetime64[ns](1), float64(7), int64(1), object(2)
memory usage: 56.0+ MB

In [7]:
# Donner à la variable date un format de date pandas
X['date'] = pd.to_datetime(X['date'])

In [ ]:
df['train'] = df['train'].astype('str')
X['train']

KeyboardInterrupt:

In [13]:
X["train"]

0         0         VBXNMF\n1         VBXNMF\n2         ...
1         0         VBXNMF\n1         VBXNMF\n2         ...
2         0         VBXNMF\n1         VBXNMF\n2         ...
3         0         VBXNMF\n1         VBXNMF\n2         ...
4         0         VBXNMF\n1         VBXNMF\n2         ...
                                ...
667259    0         VBXNMF\n1         VBXNMF\n2         ...
667260    0         VBXNMF\n1         VBXNMF\n2         ...
667261    0         VBXNMF\n1         VBXNMF\n2         ...
667262    0         VBXNMF\n1         VBXNMF\n2         ...
667263    0         VBXNMF\n1         VBXNMF\n2         ...
Name: train, Length: 667264, dtype: object

In [9]:
from sklearn import model_selection

X_train, X_test, y_train, y_test = model_selection.train_test_split(X, y, train_size = 0.7)

In [10]:
# One Hot Encoding pour passer les object en int pour pouvoir être interprétés par les modèles
from sklearn.preprocessing import OneHotEncoder

enc = OneHotEncoder(handle_unknown='warn').fit(X)

X_train = enc.fit_transform(X_train

SyntaxError: incomplete input (1584041766.py, line 6)