# Exploration des données

Ce notebook présente les données du challenge et les analyse.

In [1]:
import pandas as pd
import seaborn as sns
import numpy as np

In [2]:
# Extraction des données
X = pd.read_csv('../data/raw/x_train_final.csv')
y = pd.read_csv('../data/raw/y_train_final_j5KGWWK.csv')

X.head()

,Unnamed: 0.1,Unnamed: 0,train,gare,date,arret,p2q0,p3q0,p4q0,p0q2,p0q3,p0q4
0,0,0,VBXNMF,KYF,2023-04-03,8,0.0,0.0,1.0,-3.0,-1.0,-2.0
1,1,1,VBXNMF,JLR,2023-04-03,9,0.0,0.0,0.0,1.0,0.0,1.0
2,2,2,VBXNMF,EOH,2023-04-03,10,-1.0,0.0,0.0,-1.0,0.0,0.0
3,3,3,VBXNMF,VXY,2023-04-03,11,-1.0,-1.0,0.0,2.0,-2.0,0.0
4,4,4,VBXNMF,OCB,2023-04-03,12,-1.0,-1.0,-1.0,-1.0,3.0,2.0

In [3]:
# Suppression des colonnes du triplon d'index 

X = X.drop(columns=['Unnamed: 0.1', 'Unnamed: 0'])
y = y.drop(columns=['Unnamed: 0'])

X.head()

    train gare        date  arret  p2q0  p3q0  p4q0  p0q2  p0q3  p0q4
0  VBXNMF  KYF  2023-04-03      8   0.0   0.0   1.0  -3.0  -1.0  -2.0
1  VBXNMF  JLR  2023-04-03      9   0.0   0.0   0.0   1.0   0.0   1.0
2  VBXNMF  EOH  2023-04-03     10  -1.0   0.0   0.0  -1.0   0.0   0.0
3  VBXNMF  VXY  2023-04-03     11  -1.0  -1.0   0.0   2.0  -2.0   0.0
4  VBXNMF  OCB  2023-04-03     12  -1.0  -1.0  -1.0  -1.0   3.0   2.0

In [4]:
# Détection des données dupliquées
X.duplicated().sum()

np.int64(0)

In [5]:
# Détection des données vides ou incomplètes
pd.concat([X, y], axis = 1).isnull().any()

train    False
gare     False
date     False
arret    False
p2q0     False
p3q0     False
p4q0     False
p0q2     False
p0q3     False
p0q4     False
p0q0     False
dtype: bool

In [6]:
df_data = pd.concat([X, y], axis = 1)
df_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 667264 entries, 0 to 667263
Data columns (total 11 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   train   667264 non-null  object
 1   gare    667264 non-null  object
 2   date    667264 non-null  object
 3   arret   667264 non-null  int64
 4   p2q0    667264 non-null  float64
 5   p3q0    667264 non-null  float64
 6   p4q0    667264 non-null  float64
 7   p0q2    667264 non-null  float64
 8   p0q3    667264 non-null  float64
 9   p0q4    667264 non-null  float64
 10  p0q0    667264 non-null  float64
dtypes: float64(7), int64(1), object(3)
memory usage: 56.0+ MB

In [8]:
# Donner à la variable date un format de date pandas
X['date'] = pd.to_datetime(X['date'], format="%Y-%m-%d")

# Extraire les features temporels
X["year"] = X["date"].dt.year
X["month"] = X["date"].dt.month
X["day"] = X["date"].dt.day
X["weekday"] = X["date"].dt.weekday
X["week"] = X["date"].dt.isocalendar().week.astype(int)
X["dayofyear"] = X["date"].dt.dayofyear

# Donner une dimension cyclique aux features
X["month_sin"] = np.sin(2 * np.pi * X["month"] / 12)
X["month_cos"] = np.cos(2 * np.pi * X["month"] / 12)

X["weekday_sin"] = np.sin(2 * np.pi * X["weekday"] / 7)
X["weekday_cos"] = np.cos(2 * np.pi * X["weekday"] / 7)

X["dayofyear_sin"] = np.sin(2 * np.pi * X["dayofyear"] / 365)
X["dayofyear_cos"] = np.cos(2 * np.pi * X["dayofyear"] / 365)

# Optionnel : retirer la date brute
X = X.drop(columns=["date"])

In [9]:
from sklearn import model_selection

X_train, X_test, y_train, y_test = model_selection.train_test_split(X, y, train_size = 0.7)

In [10]:
X_train["train"].unique() # Beaucoup de catégories différentes -> binary encoding pour éviter d'avoir trop de features

array(['FJNSTM', 'CZAGCL', 'JLALRO', ..., 'JCKCAN', 'RBMHQR', 'PTFZSK'],
      shape=(37405,), dtype=object)

In [11]:
from category_encoders.binary import BinaryEncoder

# Encoder
encoder_train = BinaryEncoder(cols=["train"])

# Fit sur train
X_train = encoder_train.fit_transform(X_train)

# Transform sur test
X_test = encoder_train.transform(X_test)

In [12]:
# Encoder
encoder_gare = BinaryEncoder(cols=["gare"])

# Fit sur train
X_train = encoder_gare.fit_transform(X_train)

# Transform sur test
X_test = encoder_gare.transform(X_test)

In [23]:
from sklearn.ensemble import RandomForestClassifier
from tqdm import tqdm

n_estimators = 200

clf = RandomForestClassifier(
    max_depth=7,
    n_estimators=1,
    warm_start=True,  # permet d'ajouter des arbres petit à petit
    random_state=42
)

# Entraînement progressif
for i in tqdm(range(1, n_estimators + 1), desc="Training RandomForest"):
    clf.n_estimators = i
    clf.fit(X_train, y_train)

y_pred = clf.predict(X_test)

Training RandomForest:   0%|          | 0/200 [00:00<?, ?it/s]

c:\Users\morga\Documents\code\data_challenge\sncf_transilien_2025\ds_env\Lib\site-packages\sklearn\base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
Training RandomForest:   0%|          | 1/200 [00:01<05:52,  1.77s/it]c:\Users\morga\Documents\code\data_challenge\sncf_transilien_2025\ds_env\Lib\site-packages\sklearn\base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
Training RandomForest:   1%|          | 2/200 [00:02<04:34,  1.39s/it]c:\Users\morga\Documents\code\data_challenge\sncf_transilien_2025\ds_env\Lib\site-packages\sklearn\base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
Training RandomForest:   2%|▏         | 3/200 [00:03<03:43,  1.13s/it]c:\Users\morga\Documents\code\data_challenge\sncf_transilien_2025\ds_env\Lib\site-packages\sklearn\base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
Training RandomForest:   2%|▏         | 4/200 [00:04<03:40,  1.12s/it]c:\Users\morga\Documents\code\data_challenge\sncf_transilien_2025\ds_env\Lib\site-packages\sklearn\base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
Training RandomForest:   2%|▎         | 5/200 [00:05<03:18,  1.02s/it]c:\Users\morga\Documents\code\data_challenge\sncf_transilien_2025\ds_env\Lib\site-packages\sklearn\base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
Training RandomForest:   3%|▎         | 6/200 [00:06<03:07,  1.04it/s]c:\Users\morga\Documents\code\data_challenge\sncf_transilien_2025\ds_env\Lib\site-packages\sklearn\base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
Training RandomForest:   4%|▎         | 7/200 [00:07<03:14,  1.01s/it]c:\Users\morga\Documents\code\data_challenge\sncf_transilien_2025\ds_env\Lib\site-packages\sklearn\base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
Training RandomForest:   4%|▍         | 8/200 [00:08<03:21,  1.05s/it]c:\Users\morga\Documents\code\data_challenge\sncf_transilien_2025\ds_env\Lib\site-packages\sklearn\base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
Training RandomForest:   4%|▍         | 9/200 [00:09<03:19,  1.05s/it]c:\Users\morga\Documents\code\data_challenge\sncf_transilien_2025\ds_env\Lib\site-packages\sklearn\base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
Training RandomForest:   5%|▌         | 10/200 [00:10<03:19,  1.05s/it]c:\Users\morga\Documents\code\data_challenge\sncf_transilien_2025\ds_env\Lib\site-packages\sklearn\base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
Training RandomForest:   6%|▌         | 11/200 [00:11<03:22,  1.07s/it]c:\Users\morga\Documents\code\data_challenge\sncf_transilien_2025\ds_env\Lib\site-packages\sklearn\base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
Training RandomForest:   6%|▌         | 12/200 [00:13<03:23,  1.08s/it]c:\Users\morga\Documents\code\data_challenge\sncf_transilien_2025\ds_env\Lib\site-packages\sklearn\base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
Training RandomForest:   6%|▋         | 13/200 [00:13<03:10,  1.02s/it]c:\Users\morga\Documents\code\data_challenge\sncf_transilien_2025\ds_env\Lib\site-packages\sklearn\base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
Training RandomForest:   7%|▋         | 14/200 [00:14<02:59,  1.04it/s]c:\Users\morga\Documents\code\data_challenge\sncf_transilien_2025\ds_env\Lib\site-packages\sklearn\base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
Training RandomForest:   8%|▊         | 15/200 [00:15<02:53,  1.07it/s]c:\Users\morga\Documents\code\data_challenge\sncf_transilien_2025\ds_env\Lib\site-packages\sklearn\base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
Training RandomForest:   8%|▊         | 16/200 [00:16<02:56,  1.04it/s]c:\Users\morga\Documents\code\data_challenge\sncf_transilien_2025\ds_env\Lib\site-packages\sklearn\base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
Training RandomForest:   8%|▊         | 17/200 [00:17<02:54,  1.05it/s]c:\Users\morga\Documents\code\data_challenge\sncf_transilien_2025\ds_env\Lib\site-packages\sklearn\base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
Training RandomForest:   9%|▉         | 18/200 [00:18<02:58,  1.02it/s]c:\Users\morga\Documents\code\data_challenge\sncf_transilien_2025\ds_env\Lib\site-packages\sklearn\base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
Training RandomForest:  10%|▉         | 19/200 [00:19<02:50,  1.06it/s]c:\Users\morga\Documents\code\data_challenge\sncf_transilien_2025\ds_env\Lib\site-packages\sklearn\base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
Training RandomForest:  10%|█         | 20/200 [00:20<03:05,  1.03s/it]c:\Users\morga\Documents\code\data_challenge\sncf_transilien_2025\ds_env\Lib\site-packages\sklearn\base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
Training RandomForest:  10%|█         | 21/200 [00:21<02:56,  1.01it/s]c:\Users\morga\Documents\code\data_challenge\sncf_transilien_2025\ds_env\Lib\site-packages\sklearn\base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
Training RandomForest:  11%|█         | 22/200 [00:22<02:56,  1.01it/s]c:\Users\morga\Documents\code\data_challenge\sncf_transilien_2025\ds_env\Lib\site-packages\sklearn\base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
Training RandomForest:  12%|█▏        | 23/200 [00:23<02:49,  1.04it/s]c:\Users\morga\Documents\code\data_challenge\sncf_transilien_2025\ds_env\Lib\site-packages\sklearn\base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
Training RandomForest:  12%|█▏        | 24/200 [00:24<02:44,  1.07it/s]c:\Users\morga\Documents\code\data_challenge\sncf_transilien_2025\ds_env\Lib\site-packages\sklearn\base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
Training RandomForest:  12%|█▎        | 25/200 [00:25<02:36,  1.12it/s]c:\Users\morga\Documents\code\data_challenge\sncf_transilien_2025\ds_env\Lib\site-packages\sklearn\base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
Training RandomForest:  13%|█▎        | 26/200 [00:25<02:29,  1.17it/s]c:\Users\morga\Documents\code\data_challenge\sncf_transilien_2025\ds_env\Lib\site-packages\sklearn\base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
Training RandomForest:  14%|█▎        | 27/200 [00:26<02:29,  1.15it/s]c:\Users\morga\Documents\code\data_challenge\sncf_transilien_2025\ds_env\Lib\site-packages\sklearn\base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
Training RandomForest:  14%|█▍        | 28/200 [00:27<02:31,  1.13it/s]c:\Users\morga\Documents\code\data_challenge\sncf_transilien_2025\ds_env\Lib\site-packages\sklearn\base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
Training RandomForest:  14%|█▍        | 29/200 [00:28<02:36,  1.09it/s]c:\Users\morga\Documents\code\data_challenge\sncf_transilien_2025\ds_env\Lib\site-packages\sklearn\base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
Training RandomForest:  15%|█▌        | 30/200 [00:29<02:32,  1.11it/s]c:\Users\morga\Documents\code\data_challenge\sncf_transilien_2025\ds_env\Lib\site-packages\sklearn\base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
Training RandomForest:  16%|█▌        | 31/200 [00:30<02:27,  1.15it/s]c:\Users\morga\Documents\code\data_challenge\sncf_transilien_2025\ds_env\Lib\site-packages\sklearn\base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
Training RandomForest:  16%|█▌        | 32/200 [00:31<02:26,  1.14it/s]c:\Users\morga\Documents\code\data_challenge\sncf_transilien_2025\ds_env\Lib\site-packages\sklearn\base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
Training RandomForest:  16%|█▋        | 33/200 [00:32<02:28,  1.13it/s]c:\Users\morga\Documents\code\data_challenge\sncf_transilien_2025\ds_env\Lib\site-packages\sklearn\base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
Training RandomForest:  17%|█▋        | 34/200 [00:33<02:47,  1.01s/it]c:\Users\morga\Documents\code\data_challenge\sncf_transilien_2025\ds_env\Lib\site-packages\sklearn\base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
Training RandomForest:  18%|█▊        | 35/200 [00:34<02:51,  1.04s/it]c:\Users\morga\Documents\code\data_challenge\sncf_transilien_2025\ds_env\Lib\site-packages\sklearn\base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
Training RandomForest:  18%|█▊        | 36/200 [00:36<03:24,  1.24s/it]c:\Users\morga\Documents\code\data_challenge\sncf_transilien_2025\ds_env\Lib\site-packages\sklearn\base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
Training RandomForest:  18%|█▊        | 37/200 [00:37<03:19,  1.22s/it]c:\Users\morga\Documents\code\data_challenge\sncf_transilien_2025\ds_env\Lib\site-packages\sklearn\base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
Training RandomForest:  19%|█▉        | 38/200 [00:38<03:20,  1.24s/it]c:\Users\morga\Documents\code\data_challenge\sncf_transilien_2025\ds_env\Lib\site-packages\sklearn\base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
Training RandomForest:  20%|█▉        | 39/200 [00:39<03:04,  1.15s/it]c:\Users\morga\Documents\code\data_challenge\sncf_transilien_2025\ds_env\Lib\site-packages\sklearn\base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
Training RandomForest:  20%|██        | 40/200 [00:40<02:50,  1.07s/it]c:\Users\morga\Documents\code\data_challenge\sncf_transilien_2025\ds_env\Lib\site-packages\sklearn\base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
Training RandomForest:  20%|██        | 41/200 [00:41<02:41,  1.02s/it]c:\Users\morga\Documents\code\data_challenge\sncf_transilien_2025\ds_env\Lib\site-packages\sklearn\base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
Training RandomForest:  21%|██        | 42/200 [00:42<02:45,  1.05s/it]c:\Users\morga\Documents\code\data_challenge\sncf_transilien_2025\ds_env\Lib\site-packages\sklearn\base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
Training RandomForest:  22%|██▏       | 43/200 [00:43<02:37,  1.00s/it]c:\Users\morga\Documents\code\data_challenge\sncf_transilien_2025\ds_env\Lib\site-packages\sklearn\base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
Training RandomForest:  22%|██▏       | 44/200 [00:44<02:24,  1.08it/s]c:\Users\morga\Documents\code\data_challenge\sncf_transilien_2025\ds_env\Lib\site-packages\sklearn\base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
Training RandomForest:  22%|██▎       | 45/200 [00:45<02:22,  1.09it/s]c:\Users\morga\Documents\code\data_challenge\sncf_transilien_2025\ds_env\Lib\site-packages\sklearn\base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
Training RandomForest:  23%|██▎       | 46/200 [00:46<02:33,  1.01it/s]c:\Users\morga\Documents\code\data_challenge\sncf_transilien_2025\ds_env\Lib\site-packages\sklearn\base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
Training RandomForest:  24%|██▎       | 47/200 [00:47<02:29,  1.02it/s]c:\Users\morga\Documents\code\data_challenge\sncf_transilien_2025\ds_env\Lib\site-packages\sklearn\base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
Training RandomForest:  24%|██▍       | 48/200 [00:48<02:39,  1.05s/it]c:\Users\morga\Documents\code\data_challenge\sncf_transilien_2025\ds_env\Lib\site-packages\sklearn\base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
Training RandomForest:  24%|██▍       | 49/200 [00:50<03:04,  1.23s/it]c:\Users\morga\Documents\code\data_challenge\sncf_transilien_2025\ds_env\Lib\site-packages\sklearn\base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
Training RandomForest:  25%|██▌       | 50/200 [00:51<03:06,  1.24s/it]c:\Users\morga\Documents\code\data_challenge\sncf_transilien_2025\ds_env\Lib\site-packages\sklearn\base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
Training RandomForest:  26%|██▌       | 51/200 [00:52<03:10,  1.28s/it]c:\Users\morga\Documents\code\data_challenge\sncf_transilien_2025\ds_env\Lib\site-packages\sklearn\base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().

In [ ]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import numpy as np

# Prédictions
y_pred = clf.predict(X_test)

# MAE -> benchmark : 0.8930, meilleur actuel : 0.6346 sur X_test
mae = mean_absolute_error(y_test, y_pred)

# RMSE
rmse = np.sqrt(mean_squared_error(y_test, y_pred))

# R2 score
r2 = r2_score(y_test, y_pred)

print("MAE :", mae)
print("RMSE :", rmse)
print("R2 :", r2)

MAE : 0.7857927864921571
RMSE : 1.772259345336224
R2 : 0.0734344649126547